places=['Paris','London','Shanghai','NewYork','Washinton DC']
print(places)
sorted_place=sorted(places)
print(sorted_place)
print(places)
print(sorted_place)
sorted_place.reverse()
print(sorted(places,reverse=True))
print(sorted_place)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
print(len(places))
